module.exports = {
    // Header
    ApplicationName: "نا قل",
    Dashboard: "لوحة القيادة",
    Logout: "تسجيل خروج",
    Register: "تسجيل",
    Login: "تسجيل الدخول",

    // Footer
    CoreInfinite: "کور انفائنیٹ",

    // Landing Page
    Landing_Welcome: "مرحبا بكم في نقل",
    Landing_WelcomeSubtitle: "خدمات النقل أثناء التنقل",
    Landing_WelcomeDetails1: "مرحبا بكم في النقل! إذا كنت تاجرًا أو وسيطًا ، وتريد نشر فرص عمل للسائقين في مكان قريب ، حسنًا ، فأنت في المكان الصحيح. النقل هو وسيط بين التجار والوسطاء والسائقين ، ويوفر وسيلة سهلة وآمنة للحصول على خدمات النقل.",
    Landing_WelcomeDetails2: "لست متداول أو وسيط؟ لا داعى للقلق! نقل تقدم خدمات للسائقين أيضا. إذا كنت سائقًا ، وتبحث عن فرص عمل ، فأنت على بعد خطوة واحدة. قم بإنشاء حسابك على خدمة الويب الخاصة بنا ، وسوف نخطرك بفرص العمل على حسابك الشخصي.",
    Landing_Privacy: "خصوصية",
    Landing_PrivacySubtitle: "خصوصيتك مهمة بالنسبة لنا",
    Landing_PrivacyDetails1: "يصف بيان خصوصية النقل أنواع البيانات التي نجمعها منك ، وكيف نستخدم بياناتك ، والأسس القانونية التي يتعين علينا معالجتها لبياناتك. يصف بيان الخصوصية أيضًا كيف يستخدم النقل المحتوى الخاص بك ، وهي المعلومات التي قدمتها للنقل عبر الخدمات.",
    Landing_PrivacyDetails2: "عندما تكون المعالجة قائمة على الموافقة وإلى الحد الذي يسمح به القانون ، بالموافقة على هذه الشروط ، فإنك توافق على جمع ونقل واستخدام والكشف عن المحتوى والبيانات الخاصة بك كما هو موضح في بيان الخصوصية.",
    Landing_UserAccounts: "حسابات المستخدمين",
    Landing_UserAccountsSubtitle: "الاشتراك و / أو تسجيل الدخول",
    Landing_UserAccountsDetails: "هل تريد استخدام خدماتنا الآن؟ لا داعى للقلق! ما عليك سوى الاشتراك عن طريق ملء نماذج دقيقة و / أو تسجيل الدخول إلى ملفك الشخصي. يمكن للسائقين عرض فرص العمل على لوحات العدادات الخاصة بهم. يمكن للتجار و / أو السماسرة نشر طلبات العمل للشحن من حساباتهم.",
    Landing_Signup: "سجل",
    Landing_Login: "تسجيل الدخول",
    Landing_Location: "موقعك",
    Landing_City: "واه",
    Landing_State: "البنجاب ، باكستان",
    Landing_AroundTheGlobe: "حول العالم",
    Landing_ContactUs: "اتصل بنا",
    Landing_ContactUsDetails: "تم إنشاء النقل بواسطة Core Infinite. لمزيد من المعلومات ، قم بزيارة هذا.",

    // Login
    Login_SignIn: "تسجيل الدخول",
    Login_EmailOrUsername: "البريد الإلكتروني أو اسم المستخدم",
    Login_Password: "كلمه السر",
    Login_SignInAs: "تسجيل الدخول باسم",
    Login_Driver: "سائق",
    Login_Trader: "التاجر",
    Login_Broker: "وسيط",
    Login_TCResponsible: "مسؤول التعاون الفني",
    Login_Administrator: "مدير",
    Login_NoAccount: "لا حساب؟",
    Login_RegisterNow: "سجل الان",

    // Register
    Register_SignUp: "سجل",
    Register_Username: "اسم المستخدم",
    Register_Email: "البريد الإلكتروني",
    Register_Password: "كلمه السر",
    Register_ConfirmPassword: "تأكيد كلمة المرور",
    Register_RegisterAs: "تسجيل باسم",
    Register_Driver: "سائق",
    Register_Trader: "التاجر",
    Register_Broker: "وسيط",
    Register_TCResponsible: "مسؤول التعاون الفني",
    Register_Administrator: "مدير",
    Register_AgreeWithOur: "نتفق مع",
    Register_TermsAndConditions: "الأحكام والشروط",
    Register_HaveAnAccount: "هل لديك حساب؟",
    Register_SignInNow: "قم بتسجيل دخولك الآن!",
    Register_Next: "التالى",
    Register_TermsOfUse: "تعليمات الاستخدام",
    Register_TermsAndConditionsDetails: "خصوصيتك مهمة بالنسبة لنا. يصف بيان خصوصية النقل أنواع البيانات التي نجمعها منك ، وكيفية استخدامنا لبياناتك ، والأسس القانونية التي يتعين علينا معالجتها لبياناتك. يصف بيان الخصوصية أيضًا كيف يستخدم النقل المحتوى الخاص بك ، وهي المعلومات التي قدمتها للنقل عبر الخدمات. عندما تستند المعالجة إلى الموافقة وإلى الحد الذي يسمح به القانون ، بالموافقة على هذه الشروط ، فإنك توافق على جمع ونقل واستخدام والكشف عن المحتوى والبيانات الخاصة بك كما هو موضح في بيان الخصوصية. في بعض الحالات ، سنقدم إشعارًا منفصلاً ونطلب موافقتك على النحو المشار إليه في بيان الخصوصية.",
    Register_OK: "حسنا",
    Register_EmailError: "البريد الإلكتروني غير صالح.",
    Register_PasswordError: "كلمة المرور قصيرة جدا.",
    Register_ConfirmPasswordError: "كلمتا المرور غير متطابقتين.",
    Register_EmailUsernameError: "اسم المستخدم أو البريد الإلكتروني مأخوذ بالفعل.",
    Register_TermsError: "يجب أن توافق على الشروط والأحكام الخاصة بنا.",

    // Email Confirmation
    EmailConfirmation_EmailConfirmation: "تأكيد البريد الإلكتروني",
    EmailConfirmation_EmailConfirmationSubtitle: "لقد سلمنا رمز التأكيد إلى بريدك الإلكتروني.",
    EmailConfirmation_ConfirmationCode: "تأكيد الكود",
    EmailConfirmation_Next: "التالى",
    EmailConfirmation_ConfirmationCodeError1: "رمز التأكيد مطلوب.",
    EmailConfirmation_ConfirmationCodeError2: "Invalid code.",
};