module.exports = {
    // Header
    ApplicationName: "NAQEL",
    Dashboard: "Dashboard",
    Logout: "Logout",
    Register: "Register",
    Login: "Login",

    // Footer
    CoreInfinite: "Core Infinite",

    // Landing Page
    Landing_Welcome: "Welcome to Naqel",
    Landing_WelcomeSubtitle: "Transport Services On-The-Go",
    Landing_WelcomeDetails1: "Welcome to Naqel! If you are a trader or a broker, and you want to publish job opportunities for drivers nearby, well, you are on the right place. Naqel is a mediator among traders, brokers and drivers, and provides intuitive and secure way to get transport services.",
    Landing_WelcomeDetails2: "Not a Trader or a Broker? No worries! Naqel provides services for drivers too. If you are a driver, and you are searching for job opportunities, you are just one step away. Create your account on our Web Service, and we will notify you job oppprtunities on your personal account.",
    Landing_Privacy: "Privacy",
    Landing_PrivacySubtitle: "Your Privacy is Important to Us",
    Landing_PrivacyDetails1: "Naqel's Privacy Statement describes the types of data we collect from you, how we use your data, and the legal bases we have to process your data. The Privacy Statement also describes how Naqel uses your content, which is information submitted by you to Naqel via the Services.",
    Landing_PrivacyDetails2: "Where processing is based on consent and to the extent permitted by law, by agreeing to these Terms, you consent to Naqel's collection, use and disclosure of your content and data as described in the privacy statement.",
    Landing_UserAccounts: "User Accounts",
    Landing_UserAccountsSubtitle: "Signup and/or Login",
    Landing_UserAccountsDetails: "Do you want to use our services right now? No Worries! Just signup by filling up precise forms and/or login to your profile. Drivers can view job opprotunities on their dashboards. Traders and/or Brokers can post job requests for freight from thier accounts.",
    Landing_Signup: "Signup",
    Landing_Login: "Login",
    Landing_Location: "LOCATION",
    Landing_City: "Wah",
    Landing_State: "Punjab, Pakistan",
    Landing_AroundTheGlobe: "AROUND THE GLOBE",
    Landing_ContactUs: "CONTACT US",
    Landing_ContactUsDetails: "Naqel is created by Core Infinite. For more information, visit",

    // Login
    Login_SignIn: "Sign In",
    Login_EmailOrUsername: "Email or Username",
    Login_Password: "Password",
    Login_SignInAs: "Sign In As",
    Login_Driver: "Driver",
    Login_Trader: "Trader",
    Login_Broker: "Broker",
    Login_TCResponsible: "TC Responsible",
    Login_Administrator: "Administrator",
    Login_NoAccount: "No account?",
    Login_RegisterNow: "Register now",

    // Register
    Register_SignUp: "Sign Up",
    Register_Username: "Username",
    Register_Email: "Email",
    Register_Password: "Password",
    Register_ConfirmPassword: "Confirm Password",
    Register_RegisterAs: "Register As",
    Register_Driver: "Driver",
    Register_Trader: "Trader",
    Register_Broker: "Broker",
    Register_TCResponsible: "TC Responsible",
    Register_Administrator: "Administrator",
    Register_AgreeWithOur: "Agree with our",
    Register_TermsAndConditions: "Terms and Conditions",
    Register_HaveAnAccount: "Have an account?",
    Register_SignInNow: "Sign In Now!", 
    Register_Next: "Next",
    Register_TermsOfUse: "Terms of Use",
    Register_TermsAndConditionsDetails: "Your privacy is important to us. Naqel's Privacy Statement describes the types of data we collect from you, how we use your Data, and the legal bases we have to process your Data. The Privacy Statement also describes how Naqel uses your content, which is information submitted by you to Naqel via the Services. Where processing is based on consent and to the extent permitted by law, by agreeing to these Terms, you consent to Naqel’s collection, use and disclosure of your content and data as described in the privacy statement. In some cases, we will provide separate notice and request your consent as referenced in the privacy statement.",
    Register_OK: "OK",
    Register_EmailError: "Email is invalid.",
    Register_PasswordError: "Password is too short.",
    Register_ConfirmPasswordError: "Passwords did not match.",
    Register_EmailUsernameError: "Username or email is already taken.",
    Register_TermsError: "You must agree to our terms and conditions.",

    // Email Confirmation
    EmailConfirmation_EmailConfirmation: "Email Confirmation",
    EmailConfirmation_EmailConfirmationSubtitle: "We delivered a confirmation code to your email.",
    EmailConfirmation_ConfirmationCode: "Confirmation Code",
    EmailConfirmation_Next: "Next",
    EmailConfirmation_ConfirmationCodeError1: "Confirmation code is required.",
    EmailConfirmation_ConfirmationCodeError2: "Invalid code.",
};